var hierarchy =
[
    [ "com.clover.remotepay.sdk.AcceptPayment", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_accept_payment.html", null ],
    [ "com.clover.remotepay.sdk.ActivityMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_activity_message.html", null ],
    [ "com.clover.sdk.v3.base_.Address", "classcom_1_1clover_1_1sdk_1_1v3_1_1base___1_1_address.html", null ],
    [ "com.clover.sdk.v3.customers.Address", "classcom_1_1clover_1_1sdk_1_1v3_1_1customers_1_1_address.html", null ],
    [ "com.clover.sdk.v3.inventory.Attribute", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_attribute.html", null ],
    [ "com.clover.sdk.v3.payments.Authorization", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_authorization.html", null ],
    [ "com.clover.remotepay.sdk.BaseRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_base_request.html", [
      [ "com.clover.remotepay.sdk.CapturePreAuthRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_capture_pre_auth_request.html", null ],
      [ "com.clover.remotepay.sdk.CloseoutRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_closeout_request.html", null ],
      [ "com.clover.remotepay.sdk.CustomActivityRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_custom_activity_request.html", null ],
      [ "com.clover.remotepay.sdk.DisplayPaymentReceiptOptionsRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_display_payment_receipt_options_request.html", null ],
      [ "com.clover.remotepay.sdk.ReadCardDataRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_read_card_data_request.html", null ],
      [ "com.clover.remotepay.sdk.RefundPaymentRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_refund_payment_request.html", null ],
      [ "com.clover.remotepay.sdk.TipAdjustAuthRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_tip_adjust_auth_request.html", null ],
      [ "com.clover.remotepay.sdk.TransactionRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_transaction_request.html", [
        [ "com.clover.remotepay.sdk.AuthRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_auth_request.html", null ],
        [ "com.clover.remotepay.sdk.ManualRefundRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_manual_refund_request.html", null ],
        [ "com.clover.remotepay.sdk.PreAuthRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_pre_auth_request.html", null ],
        [ "com.clover.remotepay.sdk.SaleRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_sale_request.html", null ]
      ] ],
      [ "com.clover.remotepay.sdk.VoidPaymentRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_void_payment_request.html", null ]
    ] ],
    [ "com.clover.remotepay.sdk.BaseResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_base_response.html", [
      [ "com.clover.remotepay.sdk.CapturePreAuthResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_capture_pre_auth_response.html", null ],
      [ "com.clover.remotepay.sdk.CloseoutResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_closeout_response.html", null ],
      [ "com.clover.remotepay.sdk.CustomActivityResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_custom_activity_response.html", null ],
      [ "com.clover.remotepay.sdk.ManualRefundResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_manual_refund_response.html", null ],
      [ "com.clover.remotepay.sdk.PaymentResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_payment_response.html", [
        [ "com.clover.remotepay.sdk.AuthResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_auth_response.html", null ],
        [ "com.clover.remotepay.sdk.PreAuthResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_pre_auth_response.html", null ],
        [ "com.clover.remotepay.sdk.SaleResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_sale_response.html", null ]
      ] ],
      [ "com.clover.remotepay.sdk.PrintManualRefundDeclineReceiptMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_manual_refund_decline_receipt_message.html", null ],
      [ "com.clover.remotepay.sdk.PrintManualRefundReceiptMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_manual_refund_receipt_message.html", null ],
      [ "com.clover.remotepay.sdk.PrintPaymentDeclineReceiptMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_payment_decline_receipt_message.html", null ],
      [ "com.clover.remotepay.sdk.PrintPaymentMerchantCopyReceiptMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_payment_merchant_copy_receipt_message.html", null ],
      [ "com.clover.remotepay.sdk.PrintPaymentReceiptMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_payment_receipt_message.html", null ],
      [ "com.clover.remotepay.sdk.PrintRefundPaymentReceiptMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_refund_payment_receipt_message.html", null ],
      [ "com.clover.remotepay.sdk.ReadCardDataResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_read_card_data_response.html", null ],
      [ "com.clover.remotepay.sdk.RefundPaymentResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_refund_payment_response.html", null ],
      [ "com.clover.remotepay.sdk.ResetDeviceResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_reset_device_response.html", null ],
      [ "com.clover.remotepay.sdk.RetrieveDeviceStatusResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_retrieve_device_status_response.html", null ],
      [ "com.clover.remotepay.sdk.RetrievePaymentResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_retrieve_payment_response.html", null ],
      [ "com.clover.remotepay.sdk.RetrievePendingPaymentsResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_retrieve_pending_payments_response.html", null ],
      [ "com.clover.remotepay.sdk.TipAdded", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_tip_added.html", null ],
      [ "com.clover.remotepay.sdk.TipAdjustAuthResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_tip_adjust_auth_response.html", null ],
      [ "com.clover.remotepay.sdk.TransactionStartResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_transaction_start_response.html", null ],
      [ "com.clover.remotepay.sdk.VaultCardResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_vault_card_response.html", null ],
      [ "com.clover.remotepay.sdk.VoidPaymentResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_void_payment_response.html", null ]
    ] ],
    [ "com.clover.sdk.v3.payments.Batch", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_batch.html", null ],
    [ "com.clover.sdk.v3.payments.BatchCardTotal", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_batch_card_total.html", null ],
    [ "com.clover.sdk.v3.payments.BatchDetail", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_batch_detail.html", null ],
    [ "com.clover.sdk.v3.payments.BatchRequest", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_batch_request.html", null ],
    [ "com.clover.sdk.v3.payments.BatchTotalStats", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_batch_total_stats.html", null ],
    [ "com.clover.sdk.v3.payments.BatchTotalType", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_batch_total_type.html", null ],
    [ "com.clover.sdk.v3.customers.Card", "classcom_1_1clover_1_1sdk_1_1v3_1_1customers_1_1_card.html", null ],
    [ "com.clover.sdk.v3.payments.CardTransaction", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_card_transaction.html", null ],
    [ "com.clover.sdk.v3.inventory.Category", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_category.html", null ],
    [ "com.clover.sdk.v3.inventory.CategoryItem", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_category_item.html", null ],
    [ "com.clover.remotepay.sdk.CloverDeviceErrorEvent", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_clover_device_error_event.html", null ],
    [ "com.clover.remotepay.sdk.CloverDeviceEvent", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_clover_device_event.html", null ],
    [ "com.clover.remotepay.sdk.ConfirmPaymentRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_confirm_payment_request.html", null ],
    [ "com.clover.sdk.v3.base_.CountryInfo", "classcom_1_1clover_1_1sdk_1_1v3_1_1base___1_1_country_info.html", null ],
    [ "com.clover.sdk.v3.payments.Credit", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_credit.html", null ],
    [ "com.clover.sdk.v3.customers.Customer", "classcom_1_1clover_1_1sdk_1_1v3_1_1customers_1_1_customer.html", null ],
    [ "com.clover.sdk.v3.device.Device", "classcom_1_1clover_1_1sdk_1_1v3_1_1device_1_1_device.html", null ],
    [ "com.clover.remotepay.sdk.DeviceInfo", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_device_info.html", null ],
    [ "com.clover.sdk.v3.device.DeviceProvision", "classcom_1_1clover_1_1sdk_1_1v3_1_1device_1_1_device_provision.html", null ],
    [ "com.clover.sdk.v3.inventory.Discount", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_discount.html", null ],
    [ "com.clover.sdk.v3.order.Discount", "classcom_1_1clover_1_1sdk_1_1v3_1_1order_1_1_discount.html", null ],
    [ "com.clover.remote.order.DisplayDiscount", "classcom_1_1clover_1_1remote_1_1order_1_1_display_discount.html", null ],
    [ "com.clover.remote.order.DisplayFactory", "classcom_1_1clover_1_1remote_1_1order_1_1_display_factory.html", null ],
    [ "com.clover.remote.order.DisplayLineItem", "classcom_1_1clover_1_1remote_1_1order_1_1_display_line_item.html", null ],
    [ "com.clover.remote.order.DisplayModification", "classcom_1_1clover_1_1remote_1_1order_1_1_display_modification.html", null ],
    [ "com.clover.remote.order.operation.DisplayOperation", "classcom_1_1clover_1_1remote_1_1order_1_1operation_1_1_display_operation.html", [
      [ "com.clover.remote.order.operation.DiscountsAddedOperation", "classcom_1_1clover_1_1remote_1_1order_1_1operation_1_1_discounts_added_operation.html", null ],
      [ "com.clover.remote.order.operation.DiscountsDeletedOperation", "classcom_1_1clover_1_1remote_1_1order_1_1operation_1_1_discounts_deleted_operation.html", null ],
      [ "com.clover.remote.order.operation.LineItemsAddedOperation", "classcom_1_1clover_1_1remote_1_1order_1_1operation_1_1_line_items_added_operation.html", null ],
      [ "com.clover.remote.order.operation.LineItemsDeletedOperation", "classcom_1_1clover_1_1remote_1_1order_1_1operation_1_1_line_items_deleted_operation.html", null ],
      [ "com.clover.remote.order.operation.OrderDeletedOperation", "classcom_1_1clover_1_1remote_1_1order_1_1operation_1_1_order_deleted_operation.html", null ]
    ] ],
    [ "com.clover.remote.order.DisplayOrder", "classcom_1_1clover_1_1remote_1_1order_1_1_display_order.html", null ],
    [ "com.clover.remote.order.DisplayPayment", "classcom_1_1clover_1_1remote_1_1order_1_1_display_payment.html", null ],
    [ "com.clover.sdk.v3.customers.EmailAddress", "classcom_1_1clover_1_1sdk_1_1v3_1_1customers_1_1_email_address.html", null ],
    [ "com.clover.remotepay.sdk.ExternalDeviceStateData", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_external_device_state_data.html", null ],
    [ "com.clover.sdk.v3.order.FireOrder", "classcom_1_1clover_1_1sdk_1_1v3_1_1order_1_1_fire_order.html", null ],
    [ "com.clover.sdk.v3.payments.GatewayTxs", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_gateway_txs.html", null ],
    [ "com.clover.sdk.v3.payments.GiftCard", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_gift_card.html", null ],
    [ "com.clover.sdk.v3.payments.GiftCardResponse", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_gift_card_response.html", null ],
    [ "com.clover.sdk.v3.payments.GiftCardTransaction", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_gift_card_transaction.html", null ],
    [ "com.clover.sdk.v3.hours.HourRange", "classcom_1_1clover_1_1sdk_1_1v3_1_1hours_1_1_hour_range.html", null ],
    [ "com.clover.sdk.v3.hours.HoursSet", "classcom_1_1clover_1_1sdk_1_1v3_1_1hours_1_1_hours_set.html", null ],
    [ "com.clover.remotepay.sdk.ICloverConnector", "interfacecom_1_1clover_1_1remotepay_1_1sdk_1_1_i_clover_connector.html", [
      [ "com.clover.remotepay.sdk.CloverConnector", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_clover_connector.html", null ]
    ] ],
    [ "com.clover.remotepay.sdk.ICloverConnectorListener", "interfacecom_1_1clover_1_1remotepay_1_1sdk_1_1_i_clover_connector_listener.html", [
      [ "com.clover.remotepay.sdk.DefaultCloverConnectorListener", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_default_clover_connector_listener.html", null ]
    ] ],
    [ "com.clover.sdk.v3.inventory.Item", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_item.html", null ],
    [ "com.clover.sdk.v3.inventory.ItemGroup", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_item_group.html", null ],
    [ "com.clover.sdk.v3.inventory.ItemModifierGroup", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_item_modifier_group.html", null ],
    [ "com.clover.sdk.v3.inventory.ItemStock", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_item_stock.html", null ],
    [ "com.clover.sdk.v3.order.LineItem", "classcom_1_1clover_1_1sdk_1_1v3_1_1order_1_1_line_item.html", null ],
    [ "com.clover.sdk.v3.payments.LineItemPayment", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_line_item_payment.html", null ],
    [ "com.clover.remote.order.ListWrapper< T >", "classcom_1_1clover_1_1remote_1_1order_1_1_list_wrapper.html", null ],
    [ "com.clover.remotepay.sdk.MerchantInfo", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_merchant_info.html", null ],
    [ "com.clover.remotepay.sdk.MessageFromActivity", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_message_from_activity.html", null ],
    [ "com.clover.remotepay.sdk.MessageToActivity", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_message_to_activity.html", null ],
    [ "com.clover.sdk.v3.order.Modification", "classcom_1_1clover_1_1sdk_1_1v3_1_1order_1_1_modification.html", null ],
    [ "com.clover.sdk.v3.inventory.Modifier", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_modifier.html", null ],
    [ "com.clover.sdk.v3.inventory.ModifierGroup", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_modifier_group.html", null ],
    [ "com.clover.sdk.v3.inventory.Option", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_option.html", null ],
    [ "com.clover.sdk.v3.inventory.OptionItem", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_option_item.html", null ],
    [ "com.clover.sdk.v3.order.Order", "classcom_1_1clover_1_1sdk_1_1v3_1_1order_1_1_order.html", null ],
    [ "com.clover.sdk.v3.order.OrderTaxRate", "classcom_1_1clover_1_1sdk_1_1v3_1_1order_1_1_order_tax_rate.html", null ],
    [ "com.clover.sdk.v3.order.OrderType", "classcom_1_1clover_1_1sdk_1_1v3_1_1order_1_1_order_type.html", null ],
    [ "com.clover.sdk.v3.order.OrderTypeCategory", "classcom_1_1clover_1_1sdk_1_1v3_1_1order_1_1_order_type_category.html", null ],
    [ "com.clover.sdk.v3.payments.Payment", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_payment.html", null ],
    [ "com.clover.sdk.v3.payments.PaymentResponse", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_payment_response.html", null ],
    [ "com.clover.sdk.v3.payments.PaymentTaxRate", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_payment_tax_rate.html", null ],
    [ "com.clover.sdk.v3.customers.PhoneNumber", "classcom_1_1clover_1_1sdk_1_1v3_1_1customers_1_1_phone_number.html", null ],
    [ "com.clover.sdk.v3.printer.Printer", "classcom_1_1clover_1_1sdk_1_1v3_1_1printer_1_1_printer.html", null ],
    [ "com.clover.sdk.v3.base_.Reference", "classcom_1_1clover_1_1sdk_1_1v3_1_1base___1_1_reference.html", null ],
    [ "com.clover.sdk.v3.hours.Reference", "classcom_1_1clover_1_1sdk_1_1v3_1_1hours_1_1_reference.html", null ],
    [ "com.clover.sdk.v3.payments.Refund", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_refund.html", null ],
    [ "com.clover.remotepay.sdk.RejectPayment", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_reject_payment.html", null ],
    [ "com.clover.remotepay.sdk.SDKInfo", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_s_d_k_info.html", null ],
    [ "com.clover.sdk.v3.payments.ServerTotalStats", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_server_total_stats.html", null ],
    [ "com.clover.sdk.v3.base_.ServiceCharge", "classcom_1_1clover_1_1sdk_1_1v3_1_1base___1_1_service_charge.html", null ],
    [ "com.clover.sdk.v3.payments.ServiceChargeAmount", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_service_charge_amount.html", null ],
    [ "com.clover.sdk.v3.order.SystemOrderType", "classcom_1_1clover_1_1sdk_1_1v3_1_1order_1_1_system_order_type.html", null ],
    [ "com.clover.sdk.v3.inventory.Tag", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_tag.html", null ],
    [ "com.clover.sdk.v3.inventory.TagItem", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_tag_item.html", null ],
    [ "com.clover.sdk.v3.inventory.TagPrinter", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_tag_printer.html", null ],
    [ "com.clover.sdk.v3.payments.TaxableAmountRate", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_taxable_amount_rate.html", null ],
    [ "com.clover.sdk.v3.inventory.TaxRate", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_tax_rate.html", null ],
    [ "com.clover.sdk.v3.inventory.TaxRateItem", "classcom_1_1clover_1_1sdk_1_1v3_1_1inventory_1_1_tax_rate_item.html", null ],
    [ "com.clover.sdk.v3.base_.Tender", "classcom_1_1clover_1_1sdk_1_1v3_1_1base___1_1_tender.html", null ],
    [ "com.clover.sdk.v3.payments.Transaction", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_transaction.html", null ],
    [ "com.clover.sdk.v3.payments.TransactionSettings", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_transaction_settings.html", null ],
    [ "com.clover.sdk.v3.payments.VaultedCard", "classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_vaulted_card.html", null ],
    [ "com.clover.remotepay.sdk.VerifySignatureRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_verify_signature_request.html", null ]
];