/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2016 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.order {


public class LineItem {

  /// <summary>
  /// Unique identifier
  /// </summary>
  public String id { get; set; }

  /// <summary>
  /// The order with which the line item is associated
  /// </summary>
  public com.clover.sdk.v3.base_.Reference orderRef { get; set; }

  /// <summary>
  /// Inventory item used to create this line item
  /// </summary>
  public com.clover.sdk.v3.base_.Reference item { get; set; }

  /// <summary>
  /// Line item name
  /// </summary>
  public String name { get; set; }

  /// <summary>
  /// Alternate name of the line item
  /// </summary>
  public String alternateName { get; set; }

  /// <summary>
  /// Price of the item, typically in cents; use priceType and merchant currency to determine actual item price
  /// </summary>
  public Int64 price { get; set; }

  /// <summary>
  /// Unit quantity
  /// </summary>
  public Int32 unitQty { get; set; }

  /// <summary>
  /// Unit name (e.g. oz, lb, etc.)
  /// </summary>
  public String unitName { get; set; }

  public String itemCode { get; set; }

  public String note { get; set; }

  public Boolean printed { get; set; }

  public com.clover.sdk.v3.base_.Reference exchangedLineItem { get; set; }

  public String binName { get; set; }

  public String userData { get; set; }

  public Int64 createdTime { get; set; }

  public Int64 orderClientCreatedTime { get; set; }

  public List<com.clover.sdk.v3.order.Discount> discounts { get; set; }

  /// <summary>
  /// does the calculated flag actually do anything?
  /// </summary>
  public Int64 discountAmount { get; set; }

  public Boolean exchanged { get; set; }

  public List<com.clover.sdk.v3.order.Modification> modifications { get; set; }

  public Boolean refunded { get; set; }

  /// <summary>
  /// True if this item should be counted as revenue, for example gift cards and donations would not
  /// </summary>
  public Boolean isRevenue { get; set; }

  public List<com.clover.sdk.v3.inventory.TaxRate> taxRates { get; set; }

  /// <summary>
  /// Payments that were made for this line item
  /// </summary>
  public List<com.clover.sdk.v3.payments.LineItemPayment> payments { get; set; }

}

}
