/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2016 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.order {


public class Order {

  /// <summary>
  /// Unique identifier
  /// </summary>
  public String id { get; set; }

  /// <summary>
  /// Currency of this order
  /// </summary>
  public String currency { get; set; }

  public List<com.clover.sdk.v3.customers.Customer> customers { get; set; }

  /// <summary>
  /// The employee who took this order
  /// </summary>
  public com.clover.sdk.v3.base_.Reference employee { get; set; }

  /// <summary>
  /// Total price of the order
  /// </summary>
  public Int64 total { get; set; }

  public String title { get; set; }

  public String note { get; set; }

  public com.clover.sdk.v3.order.OrderType orderType { get; set; }

  public Boolean taxRemoved { get; set; }

  public Boolean isVat { get; set; }

  public String state { get; set; }

  public Boolean manualTransaction { get; set; }

  public Boolean groupLineItems { get; set; }

  public Boolean testMode { get; set; }

  public com.clover.sdk.v3.order.PayType payType { get; set; }

  /// <summary>
  /// Creation timestamp
  /// </summary>
  public Int64 createdTime { get; set; }

  public Int64 clientCreatedTime { get; set; }

  /// <summary>
  /// Last modified time of the order
  /// </summary>
  public Int64 modifiedTime { get; set; }

  public Int64 deletedTimestamp { get; set; }

  /// <summary>
  /// Optional service charge (gratuity) applied to this order
  /// </summary>
  public com.clover.sdk.v3.base_.ServiceCharge serviceCharge { get; set; }

  public List<com.clover.sdk.v3.order.Discount> discounts { get; set; }

  public List<com.clover.sdk.v3.order.LineItem> lineItems { get; set; }

  public List<com.clover.sdk.v3.order.OrderTaxRate> taxRates { get; set; }

  /// <summary>
  /// Payments that were made for this order
  /// </summary>
  public List<com.clover.sdk.v3.payments.Payment> payments { get; set; }

  /// <summary>
  /// Refunds that were made for this order
  /// </summary>
  public List<com.clover.sdk.v3.payments.Refund> refunds { get; set; }

  public List<com.clover.sdk.v3.payments.Credit> credits { get; set; }

  /// <summary>
  /// Voided payments associated with this order
  /// </summary>
  public List<com.clover.sdk.v3.payments.Payment> voids { get; set; }

  /// <summary>
  /// Device which created the order
  /// </summary>
  public com.clover.sdk.v3.base_.Reference device { get; set; }

}

}
