/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2016 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.order {


public class SystemOrderType {

  /// <summary>
  /// Unqiue identifier
  /// </summary>
  public String id { get; set; }

  /// <summary>
  /// Label Key
  /// </summary>
  public String labelKey { get; set; }

  /// <summary>
  /// Is for quick service restraunts?
  /// </summary>
  public Boolean isQsr { get; set; }

  /// <summary>
  /// Is for full service restraunts?
  /// </summary>
  public Boolean isFsr { get; set; }

  /// <summary>
  /// Is for retail stores?
  /// </summary>
  public Boolean isRetail { get; set; }

}

}
