/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2018 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

namespace com.clover.sdk.v3.order {


/// <summary>
/// Symbols beginning with USER_ or REJECT_ are user-initiated.  Others are client- or server-initiated.
/// </summary>
public enum VoidReason {
USER_CANCEL, TRANSPORT_ERROR, REJECT_SIGNATURE, REJECT_PARTIAL_AUTH, NOT_APPROVED, FAILED, AUTH_CLOSED_NEW_CARD, DEVELOPER_PAY_PARTIAL_AUTH, REJECT_DUPLICATE, REJECT_OFFLINE}

}
