var hierarchy =
[
    [ "com.clover.remotepay.sdk.AcceptPayment", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_accept_payment.html", null ],
    [ "com.clover.remotepay.sdk.ActivityMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_activity_message.html", null ],
    [ "com.clover.remotepay.sdk.BaseRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_base_request.html", [
      [ "com.clover.remotepay.sdk.BaseTransactionRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_base_transaction_request.html", [
        [ "com.clover.remotepay.sdk.ManualRefundRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_manual_refund_request.html", null ],
        [ "com.clover.remotepay.sdk.PreAuthRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_pre_auth_request.html", null ],
        [ "com.clover.remotepay.sdk.TransactionRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_transaction_request.html", [
          [ "com.clover.remotepay.sdk.AuthRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_auth_request.html", null ],
          [ "com.clover.remotepay.sdk.SaleRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_sale_request.html", null ]
        ] ]
      ] ],
      [ "com.clover.remotepay.sdk.CapturePreAuthRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_capture_pre_auth_request.html", null ],
      [ "com.clover.remotepay.sdk.CloseoutRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_closeout_request.html", null ],
      [ "com.clover.remotepay.sdk.CustomActivityRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_custom_activity_request.html", null ],
      [ "com.clover.remotepay.sdk.DisplayPaymentReceiptOptionsRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_display_payment_receipt_options_request.html", null ],
      [ "com.clover.remotepay.sdk.DisplayReceiptOptionsRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_display_receipt_options_request.html", null ],
      [ "com.clover.remotepay.sdk.OpenCashDrawerRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_open_cash_drawer_request.html", null ],
      [ "com.clover.remotepay.sdk.PrintJobStatusRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_job_status_request.html", null ],
      [ "com.clover.remotepay.sdk.PrintRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_request.html", null ],
      [ "com.clover.remotepay.sdk.ReadCardDataRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_read_card_data_request.html", null ],
      [ "com.clover.remotepay.sdk.RefundPaymentRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_refund_payment_request.html", null ],
      [ "com.clover.remotepay.sdk.RegisterForCustomerProvidedDataRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_register_for_customer_provided_data_request.html", null ],
      [ "com.clover.remotepay.sdk.SetCustomerInfoRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_set_customer_info_request.html", null ],
      [ "com.clover.remotepay.sdk.TipAdjustAuthRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_tip_adjust_auth_request.html", null ],
      [ "com.clover.remotepay.sdk.VoidPaymentRefundRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_void_payment_refund_request.html", null ],
      [ "com.clover.remotepay.sdk.VoidPaymentRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_void_payment_request.html", null ]
    ] ],
    [ "com.clover.remotepay.sdk.BaseResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_base_response.html", [
      [ "com.clover.remotepay.sdk.CapturePreAuthResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_capture_pre_auth_response.html", null ],
      [ "com.clover.remotepay.sdk.CloseoutResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_closeout_response.html", null ],
      [ "com.clover.remotepay.sdk.CustomActivityResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_custom_activity_response.html", null ],
      [ "com.clover.remotepay.sdk.CustomerProvidedDataEvent", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_customer_provided_data_event.html", null ],
      [ "com.clover.remotepay.sdk.DisplayReceiptOptionsResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_display_receipt_options_response.html", null ],
      [ "com.clover.remotepay.sdk.InvalidStateTransitionNotification", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_invalid_state_transition_notification.html", null ],
      [ "com.clover.remotepay.sdk.ManualRefundResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_manual_refund_response.html", null ],
      [ "com.clover.remotepay.sdk.PaymentResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_payment_response.html", [
        [ "com.clover.remotepay.sdk.AuthResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_auth_response.html", null ],
        [ "com.clover.remotepay.sdk.PreAuthResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_pre_auth_response.html", null ],
        [ "com.clover.remotepay.sdk.SaleResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_sale_response.html", null ]
      ] ],
      [ "com.clover.remotepay.sdk.PrintJobStatusResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_job_status_response.html", null ],
      [ "com.clover.remotepay.sdk.PrintManualRefundDeclineReceiptMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_manual_refund_decline_receipt_message.html", null ],
      [ "com.clover.remotepay.sdk.PrintManualRefundReceiptMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_manual_refund_receipt_message.html", null ],
      [ "com.clover.remotepay.sdk.PrintPaymentDeclineReceiptMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_payment_decline_receipt_message.html", null ],
      [ "com.clover.remotepay.sdk.PrintPaymentMerchantCopyReceiptMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_payment_merchant_copy_receipt_message.html", null ],
      [ "com.clover.remotepay.sdk.PrintPaymentReceiptMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_payment_receipt_message.html", null ],
      [ "com.clover.remotepay.sdk.PrintRefundPaymentReceiptMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_print_refund_payment_receipt_message.html", null ],
      [ "com.clover.remotepay.sdk.ReadCardDataResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_read_card_data_response.html", null ],
      [ "com.clover.remotepay.sdk.RefundPaymentResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_refund_payment_response.html", null ],
      [ "com.clover.remotepay.sdk.ResetDeviceResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_reset_device_response.html", null ],
      [ "com.clover.remotepay.sdk.RetrieveDeviceStatusResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_retrieve_device_status_response.html", null ],
      [ "com.clover.remotepay.sdk.RetrievePaymentResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_retrieve_payment_response.html", null ],
      [ "com.clover.remotepay.sdk.RetrievePendingPaymentsResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_retrieve_pending_payments_response.html", null ],
      [ "com.clover.remotepay.sdk.RetrievePrintersResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_retrieve_printers_response.html", null ],
      [ "com.clover.remotepay.sdk.TipAdded", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_tip_added.html", null ],
      [ "com.clover.remotepay.sdk.TipAdjustAuthResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_tip_adjust_auth_response.html", null ],
      [ "com.clover.remotepay.sdk.TransactionStartResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_transaction_start_response.html", null ],
      [ "com.clover.remotepay.sdk.VaultCardResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_vault_card_response.html", null ],
      [ "com.clover.remotepay.sdk.VoidPaymentRefundResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_void_payment_refund_response.html", null ],
      [ "com.clover.remotepay.sdk.VoidPaymentResponse", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_void_payment_response.html", null ]
    ] ],
    [ "com.clover.remotepay.sdk.CloverConnectorFactory", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_clover_connector_factory.html", null ],
    [ "com.clover.remotepay.sdk.CloverDeviceErrorEvent", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_clover_device_error_event.html", null ],
    [ "com.clover.remotepay.sdk.CloverDeviceEvent", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_clover_device_event.html", null ],
    [ "com.clover.remotepay.sdk.ConfirmPaymentRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_confirm_payment_request.html", null ],
    [ "com.clover.remotepay.sdk.DeviceInfo", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_device_info.html", null ],
    [ "com.clover.remotepay.sdk.service.client.DiscountAddedToDisplayOrder", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1service_1_1client_1_1_discount_added_to_display_order.html", null ],
    [ "com.clover.remotepay.sdk.service.client.DiscountRemovedFromDisplayOrder", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1service_1_1client_1_1_discount_removed_from_display_order.html", null ],
    [ "EventArgs", null, [
      [ "Clover.RemotePay.CloverEventArgs", "class_clover_1_1_remote_pay_1_1_clover_event_args.html", [
        [ "Clover.RemotePay.AuthResponseEventArgs", "class_clover_1_1_remote_pay_1_1_auth_response_event_args.html", null ],
        [ "Clover.RemotePay.CapturePreAuthResponseEventArgs", "class_clover_1_1_remote_pay_1_1_capture_pre_auth_response_event_args.html", null ],
        [ "Clover.RemotePay.CloseoutResponseEventArgs", "class_clover_1_1_remote_pay_1_1_closeout_response_event_args.html", null ],
        [ "Clover.RemotePay.ConfirmPaymentRequestEventArgs", "class_clover_1_1_remote_pay_1_1_confirm_payment_request_event_args.html", null ],
        [ "Clover.RemotePay.CustomActivityResponseEventArgs", "class_clover_1_1_remote_pay_1_1_custom_activity_response_event_args.html", null ],
        [ "Clover.RemotePay.CustomerProvidedDataResponseEventArgs", "class_clover_1_1_remote_pay_1_1_customer_provided_data_response_event_args.html", null ],
        [ "Clover.RemotePay.DeviceActivityEndEventArgs", "class_clover_1_1_remote_pay_1_1_device_activity_end_event_args.html", null ],
        [ "Clover.RemotePay.DeviceActivityStartEventArgs", "class_clover_1_1_remote_pay_1_1_device_activity_start_event_args.html", null ],
        [ "Clover.RemotePay.DeviceConnectedEventArgs", "class_clover_1_1_remote_pay_1_1_device_connected_event_args.html", null ],
        [ "Clover.RemotePay.DeviceDisconnectedEventArgs", "class_clover_1_1_remote_pay_1_1_device_disconnected_event_args.html", null ],
        [ "Clover.RemotePay.DeviceErrorEventArgs", "class_clover_1_1_remote_pay_1_1_device_error_event_args.html", null ],
        [ "Clover.RemotePay.DeviceReadyEventArgs", "class_clover_1_1_remote_pay_1_1_device_ready_event_args.html", null ],
        [ "Clover.RemotePay.DisplayReceiptOptionsResponseEventArgs", "class_clover_1_1_remote_pay_1_1_display_receipt_options_response_event_args.html", null ],
        [ "Clover.RemotePay.InvalidStateTransitionResponseEventArgs", "class_clover_1_1_remote_pay_1_1_invalid_state_transition_response_event_args.html", null ],
        [ "Clover.RemotePay.ManualRefundResponseEventArgs", "class_clover_1_1_remote_pay_1_1_manual_refund_response_event_args.html", null ],
        [ "Clover.RemotePay.MessageFromActivityEventArgs", "class_clover_1_1_remote_pay_1_1_message_from_activity_event_args.html", null ],
        [ "Clover.RemotePay.PreAuthResponseEventArgs", "class_clover_1_1_remote_pay_1_1_pre_auth_response_event_args.html", null ],
        [ "Clover.RemotePay.PrintJobStatusRequestEventArgs", "class_clover_1_1_remote_pay_1_1_print_job_status_request_event_args.html", null ],
        [ "Clover.RemotePay.PrintJobStatusResponseEventArgs", "class_clover_1_1_remote_pay_1_1_print_job_status_response_event_args.html", null ],
        [ "Clover.RemotePay.PrintManualRefundDeclineReceiptEventArgs", "class_clover_1_1_remote_pay_1_1_print_manual_refund_decline_receipt_event_args.html", null ],
        [ "Clover.RemotePay.PrintManualRefundReceiptEventArgs", "class_clover_1_1_remote_pay_1_1_print_manual_refund_receipt_event_args.html", null ],
        [ "Clover.RemotePay.PrintPaymentDeclineReceiptEventArgs", "class_clover_1_1_remote_pay_1_1_print_payment_decline_receipt_event_args.html", null ],
        [ "Clover.RemotePay.PrintPaymentMerchantCopyReceiptEventArgs", "class_clover_1_1_remote_pay_1_1_print_payment_merchant_copy_receipt_event_args.html", null ],
        [ "Clover.RemotePay.PrintPaymentReceiptEventArgs", "class_clover_1_1_remote_pay_1_1_print_payment_receipt_event_args.html", null ],
        [ "Clover.RemotePay.PrintRefundPaymentReceiptEventArgs", "class_clover_1_1_remote_pay_1_1_print_refund_payment_receipt_event_args.html", null ],
        [ "Clover.RemotePay.ReadCardDataResponseEventArgs", "class_clover_1_1_remote_pay_1_1_read_card_data_response_event_args.html", null ],
        [ "Clover.RemotePay.RefundPaymentResponseEventArgs", "class_clover_1_1_remote_pay_1_1_refund_payment_response_event_args.html", null ],
        [ "Clover.RemotePay.ResetDeviceResponseEventArgs", "class_clover_1_1_remote_pay_1_1_reset_device_response_event_args.html", null ],
        [ "Clover.RemotePay.RetrieveDeviceStatusResponseEventArgs", "class_clover_1_1_remote_pay_1_1_retrieve_device_status_response_event_args.html", null ],
        [ "Clover.RemotePay.RetrievePaymentResponseEventArgs", "class_clover_1_1_remote_pay_1_1_retrieve_payment_response_event_args.html", null ],
        [ "Clover.RemotePay.RetrievePendingPaymentsResponseEventArgs", "class_clover_1_1_remote_pay_1_1_retrieve_pending_payments_response_event_args.html", null ],
        [ "Clover.RemotePay.RetrievePrintersResponseEventArgs", "class_clover_1_1_remote_pay_1_1_retrieve_printers_response_event_args.html", null ],
        [ "Clover.RemotePay.SaleResponseEventArgs", "class_clover_1_1_remote_pay_1_1_sale_response_event_args.html", null ],
        [ "Clover.RemotePay.TipAddedEventArgs", "class_clover_1_1_remote_pay_1_1_tip_added_event_args.html", null ],
        [ "Clover.RemotePay.TipAdjustAuthResponseEventArgs", "class_clover_1_1_remote_pay_1_1_tip_adjust_auth_response_event_args.html", null ],
        [ "Clover.RemotePay.VaultCardResponseEventArgs", "class_clover_1_1_remote_pay_1_1_vault_card_response_event_args.html", null ],
        [ "Clover.RemotePay.VerifySignatureRequestEventArgs", "class_clover_1_1_remote_pay_1_1_verify_signature_request_event_args.html", null ],
        [ "Clover.RemotePay.VoidPaymentRefundResponseEventArgs", "class_clover_1_1_remote_pay_1_1_void_payment_refund_response_event_args.html", null ],
        [ "Clover.RemotePay.VoidPaymentResponseEventArgs", "class_clover_1_1_remote_pay_1_1_void_payment_response_event_args.html", null ]
      ] ]
    ] ],
    [ "com.clover.remotepay.sdk.ExternalDeviceStateData", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_external_device_state_data.html", null ],
    [ "com.clover.remotepay.sdk.ICloverConnectorListener", "interfacecom_1_1clover_1_1remotepay_1_1sdk_1_1_i_clover_connector_listener.html", [
      [ "Clover.RemotePay.CloverEventConnector", "class_clover_1_1_remote_pay_1_1_clover_event_connector.html", null ],
      [ "com.clover.remotepay.sdk.DefaultCloverConnectorListener", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_default_clover_connector_listener.html", null ]
    ] ],
    [ "IDisposable", null, [
      [ "com.clover.remotepay.sdk.ICloverConnector", "interfacecom_1_1clover_1_1remotepay_1_1sdk_1_1_i_clover_connector.html", [
        [ "Clover.RemotePay.CloverEventConnector", "class_clover_1_1_remote_pay_1_1_clover_event_connector.html", null ],
        [ "com.clover.remotepay.sdk.CloverConnector", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_clover_connector.html", null ]
      ] ]
    ] ],
    [ "com.clover.remotepay.sdk.service.client.LineItemAddedToDisplayOrder", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1service_1_1client_1_1_line_item_added_to_display_order.html", null ],
    [ "com.clover.remotepay.sdk.service.client.LineItemRemovedFromDisplayOrder", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1service_1_1client_1_1_line_item_removed_from_display_order.html", null ],
    [ "com.clover.remotepay.sdk.MerchantInfo", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_merchant_info.html", null ],
    [ "com.clover.remotepay.sdk.MessageFromActivity", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_message_from_activity.html", null ],
    [ "com.clover.remotepay.sdk.MessageToActivity", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_message_to_activity.html", null ],
    [ "com.clover.remotepay.sdk.service.client.PrintImage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1service_1_1client_1_1_print_image.html", null ],
    [ "com.clover.remotepay.sdk.service.client.PrintRequest64", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1service_1_1client_1_1_print_request64.html", null ],
    [ "com.clover.remotepay.sdk.service.client.PrintText", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1service_1_1client_1_1_print_text.html", null ],
    [ "com.clover.remotepay.sdk.RejectPayment", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_reject_payment.html", null ],
    [ "com.clover.remotepay.sdk.service.client.RejectPaymentObject", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1service_1_1client_1_1_reject_payment_object.html", null ],
    [ "com.clover.remotepay.sdk.SDKInfo", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_s_d_k_info.html", null ],
    [ "com.clover.remotepay.sdk.service.client.ShowMessage", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1service_1_1client_1_1_show_message.html", null ],
    [ "com.clover.remotepay.sdk.service.client.VaultCard", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1service_1_1client_1_1_vault_card.html", null ],
    [ "com.clover.remotepay.sdk.VerifySignatureRequest", "classcom_1_1clover_1_1remotepay_1_1sdk_1_1_verify_signature_request.html", null ]
];