var searchData=
[
  ['readcarddatarequest',['ReadCardDataRequest',['../classcom_1_1clover_1_1remotepay_1_1sdk_1_1_read_card_data_request.html',1,'com::clover::remotepay::sdk']]],
  ['readcarddataresponse',['ReadCardDataResponse',['../classcom_1_1clover_1_1remotepay_1_1sdk_1_1_read_card_data_response.html',1,'com::clover::remotepay::sdk']]],
  ['readcarddataresponseeventargs',['ReadCardDataResponseEventArgs',['../class_clover_1_1_remote_pay_1_1_read_card_data_response_event_args.html',1,'Clover::RemotePay']]],
  ['reference',['Reference',['../classcom_1_1clover_1_1sdk_1_1v3_1_1base___1_1_reference.html',1,'com.clover.sdk.v3.base_.Reference'],['../classcom_1_1clover_1_1sdk_1_1v3_1_1hours_1_1_reference.html',1,'com.clover.sdk.v3.hours.Reference']]],
  ['refund',['Refund',['../classcom_1_1clover_1_1sdk_1_1v3_1_1payments_1_1_refund.html',1,'com::clover::sdk::v3::payments']]],
  ['refundpaymentrequest',['RefundPaymentRequest',['../classcom_1_1clover_1_1remotepay_1_1sdk_1_1_refund_payment_request.html',1,'com::clover::remotepay::sdk']]],
  ['refundpaymentresponse',['RefundPaymentResponse',['../classcom_1_1clover_1_1remotepay_1_1sdk_1_1_refund_payment_response.html',1,'com::clover::remotepay::sdk']]],
  ['refundpaymentresponseeventargs',['RefundPaymentResponseEventArgs',['../class_clover_1_1_remote_pay_1_1_refund_payment_response_event_args.html',1,'Clover::RemotePay']]],
  ['registerforcustomerprovideddatarequest',['RegisterForCustomerProvidedDataRequest',['../classcom_1_1clover_1_1remotepay_1_1sdk_1_1_register_for_customer_provided_data_request.html',1,'com::clover::remotepay::sdk']]],
  ['rejectpayment',['RejectPayment',['../classcom_1_1clover_1_1remotepay_1_1sdk_1_1_reject_payment.html',1,'com::clover::remotepay::sdk']]],
  ['rejectpaymentobject',['RejectPaymentObject',['../classcom_1_1clover_1_1remotepay_1_1sdk_1_1service_1_1client_1_1_reject_payment_object.html',1,'com::clover::remotepay::sdk::service::client']]],
  ['resetdeviceresponse',['ResetDeviceResponse',['../classcom_1_1clover_1_1remotepay_1_1sdk_1_1_reset_device_response.html',1,'com::clover::remotepay::sdk']]],
  ['resetdeviceresponseeventargs',['ResetDeviceResponseEventArgs',['../class_clover_1_1_remote_pay_1_1_reset_device_response_event_args.html',1,'Clover::RemotePay']]],
  ['retrievedevicestatusresponse',['RetrieveDeviceStatusResponse',['../classcom_1_1clover_1_1remotepay_1_1sdk_1_1_retrieve_device_status_response.html',1,'com::clover::remotepay::sdk']]],
  ['retrievedevicestatusresponseeventargs',['RetrieveDeviceStatusResponseEventArgs',['../class_clover_1_1_remote_pay_1_1_retrieve_device_status_response_event_args.html',1,'Clover::RemotePay']]],
  ['retrievepaymentresponse',['RetrievePaymentResponse',['../classcom_1_1clover_1_1remotepay_1_1sdk_1_1_retrieve_payment_response.html',1,'com::clover::remotepay::sdk']]],
  ['retrievepaymentresponseeventargs',['RetrievePaymentResponseEventArgs',['../class_clover_1_1_remote_pay_1_1_retrieve_payment_response_event_args.html',1,'Clover::RemotePay']]],
  ['retrievependingpaymentsresponse',['RetrievePendingPaymentsResponse',['../classcom_1_1clover_1_1remotepay_1_1sdk_1_1_retrieve_pending_payments_response.html',1,'com::clover::remotepay::sdk']]],
  ['retrievependingpaymentsresponseeventargs',['RetrievePendingPaymentsResponseEventArgs',['../class_clover_1_1_remote_pay_1_1_retrieve_pending_payments_response_event_args.html',1,'Clover::RemotePay']]],
  ['retrieveprintersresponse',['RetrievePrintersResponse',['../classcom_1_1clover_1_1remotepay_1_1sdk_1_1_retrieve_printers_response.html',1,'com::clover::remotepay::sdk']]],
  ['retrieveprintersresponseeventargs',['RetrievePrintersResponseEventArgs',['../class_clover_1_1_remote_pay_1_1_retrieve_printers_response_event_args.html',1,'Clover::RemotePay']]]
];
