var searchData=
[
  ['base_5f',['base_',['../namespacecom_1_1clover_1_1sdk_1_1v3_1_1base__.html',1,'com::clover::sdk::v3']]],
  ['client',['client',['../namespacecom_1_1clover_1_1remotepay_1_1sdk_1_1service_1_1client.html',1,'com::clover::remotepay::sdk::service']]],
  ['clover',['Clover',['../namespace_clover.html',1,'Clover'],['../namespacecom_1_1clover.html',1,'com.clover']]],
  ['com',['com',['../namespacecom.html',1,'']]],
  ['customers',['customers',['../namespacecom_1_1clover_1_1sdk_1_1v3_1_1customers.html',1,'com::clover::sdk::v3']]],
  ['device',['device',['../namespacecom_1_1clover_1_1sdk_1_1v3_1_1device.html',1,'com::clover::sdk::v3']]],
  ['hours',['hours',['../namespacecom_1_1clover_1_1sdk_1_1v3_1_1hours.html',1,'com::clover::sdk::v3']]],
  ['inventory',['inventory',['../namespacecom_1_1clover_1_1sdk_1_1v3_1_1inventory.html',1,'com::clover::sdk::v3']]],
  ['operation',['operation',['../namespacecom_1_1clover_1_1remote_1_1order_1_1operation.html',1,'com::clover::remote::order']]],
  ['order',['order',['../namespacecom_1_1clover_1_1remote_1_1order.html',1,'com.clover.remote.order'],['../namespacecom_1_1clover_1_1sdk_1_1v3_1_1order.html',1,'com.clover.sdk.v3.order']]],
  ['payments',['payments',['../namespacecom_1_1clover_1_1sdk_1_1v3_1_1payments.html',1,'com::clover::sdk::v3']]],
  ['printer',['printer',['../namespacecom_1_1clover_1_1sdk_1_1v3_1_1printer.html',1,'com::clover::sdk::v3']]],
  ['properties',['Properties',['../namespacecom_1_1clover_1_1sdk_1_1v3_1_1_properties.html',1,'com::clover::sdk::v3']]],
  ['remote',['remote',['../namespacecom_1_1clover_1_1remote.html',1,'com::clover']]],
  ['remotepay',['RemotePay',['../namespace_clover_1_1_remote_pay.html',1,'Clover.RemotePay'],['../namespacecom_1_1clover_1_1remotepay.html',1,'com.clover.remotepay']]],
  ['sdk',['sdk',['../namespacecom_1_1clover_1_1remotepay_1_1sdk.html',1,'com.clover.remotepay.sdk'],['../namespacecom_1_1clover_1_1sdk.html',1,'com.clover.sdk']]],
  ['service',['service',['../namespacecom_1_1clover_1_1remotepay_1_1sdk_1_1service.html',1,'com::clover::remotepay::sdk']]],
  ['v3',['v3',['../namespacecom_1_1clover_1_1sdk_1_1v3.html',1,'com::clover::sdk']]]
];
