/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2018 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.inventory {


public class Item {

  /// <summary>
  /// Unique identifier
  /// </summary>
  public String id { get; set; }

  /// <summary>
  /// True if this item is hidden from register
  /// </summary>
  public Boolean hidden { get; set; }

  /// <summary>
  /// Reference to an item group
  /// </summary>
  public com.clover.sdk.v3.base_.Reference itemGroup { get; set; }

  /// <summary>
  /// Name of the item
  /// </summary>
  public String name { get; set; }

  /// <summary>
  /// Alternate name of the item
  /// </summary>
  public String alternateName { get; set; }

  /// <summary>
  /// Product code, e.g. UPC or EAN
  /// </summary>
  public String code { get; set; }

  /// <summary>
  /// SKU of the item
  /// </summary>
  public String sku { get; set; }

  /// <summary>
  /// Price of the item, typically in cents; use priceType and merchant currency to determine actual item price
  /// </summary>
  public Int64 price { get; set; }

  public com.clover.sdk.v3.inventory.PriceType priceType { get; set; }

  /// <summary>
  /// Flag to indicate whether or not to use default tax rates
  /// </summary>
  public Boolean defaultTaxRates { get; set; }

  /// <summary>
  /// Unit name, e.g. oz, lb
  /// </summary>
  public String unitName { get; set; }

  /// <summary>
  /// Cost of the item to merchant, as opposed to customer price
  /// </summary>
  public Int64 cost { get; set; }

  /// <summary>
  /// True if this item should be counted as revenue, for example gift cards and donations would not
  /// </summary>
  public Boolean isRevenue { get; set; }

  /// <summary>
  /// DEPRECATED: use itemStock instead
  /// </summary>
  public Int64 stockCount { get; set; }

  public List<com.clover.sdk.v3.inventory.TaxRate> taxRates { get; set; }

  public List<com.clover.sdk.v3.inventory.ModifierGroup> modifierGroups { get; set; }

  /// <summary>
  /// Categories associated with this item
  /// </summary>
  public List<com.clover.sdk.v3.inventory.Category> categories { get; set; }

  /// <summary>
  /// Tags associated with this item
  /// </summary>
  public List<com.clover.sdk.v3.inventory.Tag> tags { get; set; }

  /// <summary>
  /// Item stock attribute that can be expanded to show stock quantity
  /// </summary>
  public com.clover.sdk.v3.inventory.ItemStock itemStock { get; set; }

  public Int64 modifiedTime { get; set; }

}

}
