/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2018 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.inventory {


public class ModifierGroup {

  public String id { get; set; }

  /// <summary>
  /// Name of the modifier group
  /// </summary>
  public String name { get; set; }

  public String alternateName { get; set; }

  public Int32 minRequired { get; set; }

  public Int32 maxAllowed { get; set; }

  public Boolean showByDefault { get; set; }

  public List<com.clover.sdk.v3.inventory.Modifier> modifiers { get; set; }

  /// <summary>
  /// The ordered, comma-separated list of modifier ids in this group.
  /// </summary>
  public String modifierIds { get; set; }

  public List<com.clover.sdk.v3.base_.Reference> items { get; set; }

}

}
