/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2016 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

namespace com.clover.sdk.v3.payments {


public enum AVSResult {
SUCCESS, ZIP_CODE_MATCH, ZIP_CODE_MATCH_ADDRESS_NOT_CHECKED, ADDRESS_MATCH, ADDRESS_MATCH_ZIP_NOT_CHECKED, NEITHER_MATCH, SERVICE_FAILURE, SERVICE_UNAVAILABLE, NOT_CHECKED, ZIP_CODE_NOT_MATCHED_ADDRESS_NOT_CHECKED, ADDRESS_NOT_MATCHED_ZIP_CODE_NOT_CHECKED}

}
