/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2018 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.payments {


public class Batch {

  public String id { get; set; }

  public Int64 merchantId { get; set; }

  public Int64 firstGatewayTxId { get; set; }

  public Int64 lastGatewayTxId { get; set; }

  /// <summary>
  /// The id of employee who executed batch
  /// </summary>
  public Int64 accountId { get; set; }

  /// <summary>
  /// The number of transactions being batched
  /// </summary>
  public Int64 txCount { get; set; }

  /// <summary>
  /// Total amount closed
  /// </summary>
  public Int64 totalBatchAmount { get; set; }

  /// <summary>
  /// List of devices in batch
  /// </summary>
  public String devices { get; set; }

  public com.clover.sdk.v3.payments.BatchState state { get; set; }

  public com.clover.sdk.v3.payments.BatchType batchType { get; set; }

  /// <summary>
  /// Created time of batch
  /// </summary>
  public Int64 createdTime { get; set; }

  /// <summary>
  /// Modified time of batch
  /// </summary>
  public Int64 modifiedTime { get; set; }

  /// <summary>
  /// Details split based on card / employees
  /// </summary>
  public com.clover.sdk.v3.payments.BatchDetail batchDetails { get; set; }

}

}
