/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2018 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.payments {


public class Credit {

  /// <summary>
  /// Unique identifier
  /// </summary>
  public String id { get; set; }

  /// <summary>
  /// The order with which the credit is associated
  /// </summary>
  public com.clover.sdk.v3.base_.Reference orderRef { get; set; }

  /// <summary>
  /// Device which processed this credit
  /// </summary>
  public com.clover.sdk.v3.base_.Reference device { get; set; }

  /// <summary>
  /// The tender type associated with this payment, e.g. credit card, cash, etc.
  /// </summary>
  public com.clover.sdk.v3.base_.Tender tender { get; set; }

  /// <summary>
  /// The employee who processed the payment
  /// </summary>
  public com.clover.sdk.v3.base_.Reference employee { get; set; }

  /// <summary>
  /// Customer who received the credit/refund
  /// </summary>
  public com.clover.sdk.v3.customers.Customer customers { get; set; }

  /// <summary>
  /// Amount paid
  /// </summary>
  public Int64 amount { get; set; }

  /// <summary>
  /// Amount paid in tax
  /// </summary>
  public Int64 taxAmount { get; set; }

  public List<com.clover.sdk.v3.payments.TaxableAmountRate> taxRates { get; set; }

  /// <summary>
  /// Time payment was recorded on server
  /// </summary>
  public Int64 createdTime { get; set; }

  public Int64 clientCreatedTime { get; set; }

  /// <summary>
  /// Information about the card used for credit/debit card payments
  /// </summary>
  public com.clover.sdk.v3.payments.CardTransaction cardTransaction { get; set; }

  public Boolean voided { get; set; }

  public String voidReason { get; set; }

  /// <summary>
  /// The external reference id if associated with the payment
  /// </summary>
  public String externalReferenceId { get; set; }
}

}
