/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.payments
{
    public class CustomFieldDetails
    {
        public string Name { get; set; }

        public string Value { get; set; }

    }
}
