/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

namespace com.clover.sdk.v3.payments
{


    public enum DataEntryLocation
    {
        ON_SCREEN, ON_PAPER, NONE
    }

}
