/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2016 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.payments {


public class GatewayTxs {

  public Int64 merchantGatewayId { get; set; }

  public String clientId { get; set; }

  public Int64 amount { get; set; }

  public Int64 adjustAmount { get; set; }

  public Int64 taxAmount { get; set; }

  public Int64 tipAmount { get; set; }

  public com.clover.sdk.v3.payments.Currency currency { get; set; }

  public com.clover.sdk.v3.payments.GatewayTxState state { get; set; }

  public Int64 retries { get; set; }

  public com.clover.sdk.v3.payments.GatewayTxType type { get; set; }

  public com.clover.sdk.v3.payments.CardEntryType entryType { get; set; }

  public String responseCode { get; set; }

  public String responseMessage { get; set; }

  public String first4 { get; set; }

  public String last4 { get; set; }

  public com.clover.sdk.v3.payments.CardType cardType { get; set; }

  public String refnum { get; set; }

  public String token { get; set; }

  public String authcode { get; set; }

  public String employeeId { get; set; }

  public String extra { get; set; }

  public Boolean captured { get; set; }

  public String swiperSerial { get; set; }

  public String ksnPrefix { get; set; }

  public Int64 createdTime { get; set; }

  public Int64 modifiedTime { get; set; }

  public Int64 refundId { get; set; }

  public Int64 paymentRefundId { get; set; }

}

}
