/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2018 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.payments {


public class GiftCardResponse {

  public com.clover.sdk.v3.payments.TxType txType { get; set; }

  public com.clover.sdk.v3.payments.GiftCardState state { get; set; }

  /// <summary>
  /// Transaction Amount
  /// </summary>
  public Int64 requestAmount { get; set; }

  public com.clover.sdk.v3.payments.Payment payment { get; set; }

  public String responseMessage { get; set; }

  public Boolean requestSuccessful { get; set; }

  public String accountNumber { get; set; }

  public String giftCardTxUuid { get; set; }

  public String transactionId { get; set; }

  public String referenceUuid { get; set; }

  public String authCode { get; set; }

  public Int64 begBal { get; set; }

  public Int64 endBal { get; set; }

  public Int64 holdBal { get; set; }

}

}
