/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2018 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.payments {


public class LineItemPayment {

  /// <summary>
  /// Unique identifier; TBD this is confusing because it's used as either line item id or payment id
  /// </summary>
  public String id { get; set; }

  /// <summary>
  /// The line item with which the line item payment is associated
  /// </summary>
  public com.clover.sdk.v3.base_.Reference lineItemRef { get; set; }

  /// <summary>
  /// The payment with which the line item payment is associated
  /// </summary>
  public com.clover.sdk.v3.base_.Reference paymentRef { get; set; }

  /// <summary>
  /// Percent of this line item covered by this payment
  /// </summary>
  public Int64 percentage { get; set; }

  /// <summary>
  /// Bin this line item payment was for
  /// </summary>
  public String binName { get; set; }

  /// <summary>
  /// Payment has been refunded
  /// </summary>
  public Boolean refunded { get; set; }

}

}
