/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2018 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.payments {


public class Payment {

  /// <summary>
  /// Unique identifier
  /// </summary>
  public String id { get; set; }

  /// <summary>
  /// The order with which the payment is associated
  /// </summary>
  public com.clover.sdk.v3.base_.Reference order { get; set; }

  /// <summary>
  /// Device which processed the transaction for this payment
  /// </summary>
  public com.clover.sdk.v3.base_.Reference device { get; set; }

  /// <summary>
  /// The tender type associated with this payment, e.g. credit card, cash, etc.
  /// </summary>
  public com.clover.sdk.v3.base_.Tender tender { get; set; }

  /// <summary>
  /// Total amount paid
  /// </summary>
  public Int64 amount { get; set; }

  /// <summary>
  /// Amount paid in tips
  /// </summary>
  public Int64 tipAmount { get; set; }

  /// <summary>
  /// Amount paid in tax
  /// </summary>
  public Int64 taxAmount { get; set; }

  /// <summary>
  /// Amount given back in a cash back transaction
  /// </summary>
  public Int64 cashbackAmount { get; set; }

  /// <summary>
  /// Amount of cash given by the customer
  /// </summary>
  public Int64 cashTendered { get; set; }

  public String externalPaymentId { get; set; }

  /// <summary>
  /// The employee who processed the payment
  /// </summary>
  public com.clover.sdk.v3.base_.Reference employee { get; set; }

  /// <summary>
  /// Time payment was recorded on server
  /// </summary>
  public Int64 createdTime { get; set; }

  public Int64 clientCreatedTime { get; set; }

  /// <summary>
  /// Last modified time of the payment
  /// </summary>
  public Int64 modifiedTime { get; set; }

  public Boolean offline { get; set; }

  public com.clover.sdk.v3.payments.Result result { get; set; }

  /// <summary>
  /// Information about the card used for credit/debit card payments
  /// </summary>
  public com.clover.sdk.v3.payments.CardTransaction cardTransaction { get; set; }

  /// <summary>
  /// Amount record as a service charge
  /// </summary>
  public com.clover.sdk.v3.payments.ServiceChargeAmount serviceCharge { get; set; }

  public List<com.clover.sdk.v3.payments.PaymentTaxRate> taxRates { get; set; }

  public List<com.clover.sdk.v3.payments.Refund> refunds { get; set; }

  public String note { get; set; }

  public List<com.clover.sdk.v3.payments.LineItemPayment> lineItemPayments { get; set; }

  /// <summary>
  /// If voided, the reason why (when available)
  /// </summary>
  public com.clover.sdk.v3.order.VoidReason voidReason { get; set; }

}

}
