/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2018 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.payments {


public class Refund {

  /// <summary>
  /// Unique identifier
  /// </summary>
  public string id { get; set; }

  /// <summary>
  /// The order with which the refund is associated
  /// </summary>
  public com.clover.sdk.v3.base_.Reference orderRef { get; set; }

  /// <summary>
  /// Device which processed the transaction for this refund
  /// </summary>
  public com.clover.sdk.v3.base_.Reference device { get; set; }

  /// <summary>
  /// Total amount refunded, including tax
  /// </summary>
  public long? amount { get; set; }

  /// <summary>
  /// Tax amount refunded
  /// </summary>
  public long? taxAmount { get; set; }

  /// <summary>
  /// The time when the refund was recorded on the server
  /// </summary>
  public long? createdTime { get; set; }

  /// <summary>
  /// The time when the refund was recorded on the client
  /// </summary>
  public long? clientCreatedTime { get; set; }

  /// <summary>
  /// The payment with which the refund is associated
  /// </summary>
  public com.clover.sdk.v3.base_.Reference payment { get; set; }

  public com.clover.sdk.v3.base_.Reference employee { get; set; }

  public List<com.clover.sdk.v3.base_.Reference> lineItems { get; set; }

  /// <summary>
  /// The tender type associated with this payment, e.g. credit card, cash, etc.
  /// </summary>
  public com.clover.sdk.v3.base_.Tender overrideMerchantTender { get; set; }

  public List<com.clover.sdk.v3.payments.TaxableAmountRate> taxableAmountRates { get; set; }

  public com.clover.sdk.v3.payments.ServiceChargeAmount serviceChargeAmount { get; set; }

  /// <summary>
  /// The external reference id if associated with the refund
  /// </summary>
  public string externalReferenceId { get; set; }
}

}
