/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

namespace com.clover.sdk.v3.payments
{


    public enum TipMode
    {
        TIP_PROVIDED, ON_SCREEN_BEFORE_PAYMENT, ON_SCREEN_AFTER_PAYMENT, ON_PAPER, NO_TIP
    }

}
