/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2016 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.device {


public class DeviceProvision {

  /// <summary>
  /// Unique identifier
  /// </summary>
  public String id { get; set; }

  public com.clover.sdk.v3.base_.Reference deviceRef { get; set; }

  public com.clover.sdk.v3.device.DeviceProvisionState state { get; set; }

  public String lastActivationCode { get; set; }

  public String activationCode { get; set; }

  public Boolean emailSent { get; set; }

  public Boolean hasShipment { get; set; }

  public String serialNumber { get; set; }

  public com.clover.sdk.v3.base_.Reference merchant { get; set; }

  public String deviceType { get; set; }

  public Int64 provisionedTime { get; set; }

  public Int64 activatedTime { get; set; }

  public com.clover.sdk.v3.base_.Reference reseller { get; set; }

  public com.clover.sdk.v3.base_.Reference currentRom { get; set; }

}

}
