/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Copyright (C) 2016 Clover Network, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;

namespace com.clover.sdk.v3.base_ {


public class Tender {

  /// <summary>
  /// Unique identifier
  /// </summary>
  public String id { get; set; }

  /// <summary>
  /// If this merchant tender is editable
  /// </summary>
  public Boolean editable { get; set; }

  /// <summary>
  /// Label Key
  /// </summary>
  public String labelKey { get; set; }

  /// <summary>
  /// Label Key
  /// </summary>
  public String label { get; set; }

  /// <summary>
  /// If this tender opens the cash drawer
  /// </summary>
  public Boolean opensCashDrawer { get; set; }

  /// <summary>
  /// Allow tipping on payment from tender
  /// </summary>
  public Boolean supportsTipping { get; set; }

  /// <summary>
  /// If this merchant tender is enabled
  /// </summary>
  public Boolean enabled { get; set; }

  /// <summary>
  /// If this merchant tender is visible
  /// </summary>
  public Boolean visible { get; set; }

  /// <summary>
  /// Label Key
  /// </summary>
  public String instructions { get; set; }

}

}
